# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-30 23:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appesi', '0005_cursomod_tipopagof'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accesoriomod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.FileField(default='', upload_to='')),
                ('precio', models.CharField(default='', max_length=15)),
                ('otros', models.CharField(default='', max_length=1500)),
            ],
        ),
        migrations.CreateModel(
            name='Computadoramod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.FileField(default='', upload_to='')),
                ('hdd', models.CharField(default='', max_length=15)),
                ('ram', models.CharField(default='', max_length=30)),
                ('pantalla', models.CharField(default='', max_length=30)),
                ('precio', models.CharField(default='', max_length=15)),
                ('otros', models.CharField(default='', max_length=1500)),
            ],
        ),
        migrations.CreateModel(
            name='Marcamod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Tipoaccesoriomod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoaccesorio', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Tipocomputadoramod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='computadoramod',
            name='marcaf',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='appesi.Marcamod'),
        ),
        migrations.AddField(
            model_name='computadoramod',
            name='tipocomputadoraf',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='appesi.Tipocomputadoramod'),
        ),
        migrations.AddField(
            model_name='accesoriomod',
            name='marcaf',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='appesi.Marcamod'),
        ),
        migrations.AddField(
            model_name='accesoriomod',
            name='tipoaccesoriof',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='appesi.Tipoaccesoriomod'),
        ),
    ]
